// Mocks generated by Mockito 5.4.4 from annotations
// in msig_food/test/mock/mockito/repository/favorite/base_favorite_repository.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:msig_food/src/src.dart' as _i2;
import 'package:msig_food/src/src.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoriteData_0 extends _i1.SmartFake implements _i2.FavoriteData {
  _FakeFavoriteData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BaseFavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseFavoriteRepository extends _i1.Mock
    implements _i3.BaseFavoriteRepository {
  @override
  _i4.Future<List<_i2.FavoriteData>> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.FavoriteData>>.value(<_i2.FavoriteData>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.FavoriteData>>.value(<_i2.FavoriteData>[]),
      ) as _i4.Future<List<_i2.FavoriteData>>);

  @override
  _i4.Future<_i2.FavoriteData> getFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getFavorite,
          [id],
        ),
        returnValue: _i4.Future<_i2.FavoriteData>.value(_FakeFavoriteData_0(
          this,
          Invocation.method(
            #getFavorite,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.FavoriteData>.value(_FakeFavoriteData_0(
          this,
          Invocation.method(
            #getFavorite,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.FavoriteData>);

  @override
  _i4.Future<int> insertFavorite(_i2.FavoriteCompanion? favoriteData) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFavorite,
          [favoriteData],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFavorite,
          [id],
        ),
        returnValue: _i4.Future<int>.value(0),
        returnValueForMissingStub: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}
